
$origin 0 0 0 90
$ambientboost
$opaque
$staticprop

$modelname props_vehicles/ussr/zis-6_katusha_destroyed

$model "ZiS-6" ussr_ZiS-6_Katusha_destroyed

$shadowlod
{
	replacemodel ussr_ZiS-6_Katusha_destroyed ussr_ZiS-6_Katusha_destroyed_lod1
	nofacial
}

$surfaceprop concrete

$contents solid

$illumposition 0.45 5.551 55.645

$cdmaterials models/props_vehicles/ussr/zis

$bbox -148.944 -58.462 -73.993 180.34 59.96 93.535

$sequence idle {
	ussr_ZiS-6_Katusha_destroyed
	fps 1
}
